### ISSUE TITLE
Error: unable to find directory entry in pubspec.yaml: E:\Flutter_Projects\Shots\assets\packs\

### ISSUE THREAD

**Issue by stonega** [themindstorm/Shots#2]
Hi, I try to run on my desktop, such error happened. Did I miss something?
```
Launching lib\main.dart on Pixel 3 XL in debug mode...
Error: unable to find directory entry in pubspec.yaml: E:\Flutter_Projects\Shots\assets\packs\
√ Built build\app\outputs\apk\debug\app-debug.apk.
```

**Comment by ninest** [comment]
Yes, the packs (yaml files) are missing. I removed them from the most recent commits because I moved them to a new repository.

I'll make a quick fix and add the test pack to this repository so you can test it problem free.

Give me some time, and I'll notify you when it's done!

**Comment by ninest** [comment]
Try running the latest commit. I've added the test card pack (test.yml). You will see other card packs in metadata.yml. Since they don't exist for you, the app will just ignore them quietly. In the "Choose packs" page, you'll only see the "Test" card pack.

The reason I'm not including the card packs here is because I'm going to use a different repository solely for them. That way, we can keep the app code and card packs separate. I'll comment the repo link when it's ready

**Comment by stonega** [comment]
Thanks, got it
